add test report to CI

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -27,5 +27,15 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml
+    - name: Build and Test with Maven
+      run: mvn -B verify --file pom.xml
+      
+    - name: Publish Test Results
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # Run this step even if tests fail
+      with:
+        name: Maven Test Results
+        path: |
+           **/target/surefire-reports/*.xml
+           **/target/failsafe-reports/*.xml
+        reporter: java-junit
